# Use YAML for configuration since it allows comments like this
site_name: CATHY days 2023
description: CATHY days 2023 website
author: Benjamin Mary
language: en
repository: BenjMy/CATHY_days_2023
favicon: images/sphx_glr_pyCATHY_weilletal_thumb.png
logo: images/sphx_glr_pyCATHY_weilletal_thumb.png
menu:
  - [Home, index]  
  - [Committee, committees]
  - [About, about]
ignore:
  - README.md
  - config-alternative.json
  - Makefile
keywords: 'Catchment Hydrology'
language: en

