# Use YAML for configuration since it allows comments like this
site_name: 2nd Agrogeophysics seminar
description: 2ndAgrogeophysics seminar website
author: Benjamin Mary
language: en
repository: agrogeophy/2nd_agrogeophysics_seminar
favicon: images/Garre_drawing1.png
logo: images/Garre_drawing2.png
menu:
  - [Home, index]  
  - [Committee, committees]
  - [About, about]
ignore:
  - README.md
  - config-alternative.json
  - Makefile
keywords: 'agrogeophysics, hydrogeophysics, ERT, EMI, GPR, seismic, NMR, applied geophysics, remote sensing, open-source'
language: en

